apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: go-microservice
        group: go-microservice
    name: go-microservice
spec:
    replicas: 3
    selector:
        matchLabels:
            app: go-microservice
    strategy: {}
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: go-microservice
                group: go-microservice
        spec:
            containers:
                - image: localhost:32000/go-microservice
                  imagePullPolicy: Always
                  name: go-microservice
                  resources: {}
                  command: [ "./go-microservice", "-config", "config/k8s.json"]
                  livenessProbe:
                      httpGet:
                          path: /health/liveness
                          port: 8080
                      initialDelaySeconds: 3
                      periodSeconds: 3
                  readinessProbe:
                      httpGet:
                          path: /health/readiness
                          port: 8080
                      initialDelaySeconds: 3
                      periodSeconds: 3

status: {}
---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        app: go-microservice
        group: go-microservice
    name: go-microservice
spec:
    ports:
        - name: 8080-8080
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: go-microservice
    type: ClusterIP
status:
    loadBalancer: {}
